// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.BankTransferDataOnDemand;
import orko.dev.controlgastos.model.BankTransferIntegrationTest;
import orko.dev.controlgastos.repository.BankTransferRepository;
import orko.dev.controlgastos.service.BankTransferService;

privileged aspect BankTransferIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BankTransferIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BankTransferIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BankTransferIntegrationTest: @Transactional;
    
    @Autowired
    private BankTransferDataOnDemand BankTransferIntegrationTest.dod;
    
    @Autowired
    BankTransferService BankTransferIntegrationTest.bankTransferService;
    
    @Autowired
    BankTransferRepository BankTransferIntegrationTest.bankTransferRepository;
    
    @Test
    public void BankTransferIntegrationTest.testCountAllBankTransfers() {
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", dod.getRandomBankTransfer());
        long count = bankTransferService.countAllBankTransfers();
        Assert.assertTrue("Counter for 'BankTransfer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BankTransferIntegrationTest.testFindBankTransfer() {
        BankTransfer obj = dod.getRandomBankTransfer();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to provide an identifier", id);
        obj = bankTransferService.findBankTransfer(id);
        Assert.assertNotNull("Find method for 'BankTransfer' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BankTransfer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BankTransferIntegrationTest.testFindAllBankTransfers() {
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", dod.getRandomBankTransfer());
        long count = bankTransferService.countAllBankTransfers();
        Assert.assertTrue("Too expensive to perform a find all test for 'BankTransfer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BankTransfer> result = bankTransferService.findAllBankTransfers();
        Assert.assertNotNull("Find all method for 'BankTransfer' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BankTransfer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BankTransferIntegrationTest.testFindBankTransferEntries() {
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", dod.getRandomBankTransfer());
        long count = bankTransferService.countAllBankTransfers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BankTransfer> result = bankTransferService.findBankTransferEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BankTransfer' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BankTransfer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BankTransferIntegrationTest.testFlush() {
        BankTransfer obj = dod.getRandomBankTransfer();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to provide an identifier", id);
        obj = bankTransferService.findBankTransfer(id);
        Assert.assertNotNull("Find method for 'BankTransfer' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBankTransfer(obj);
        Integer currentVersion = obj.getVersion();
        bankTransferRepository.flush();
        Assert.assertTrue("Version for 'BankTransfer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BankTransferIntegrationTest.testUpdateBankTransferUpdate() {
        BankTransfer obj = dod.getRandomBankTransfer();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to provide an identifier", id);
        obj = bankTransferService.findBankTransfer(id);
        boolean modified =  dod.modifyBankTransfer(obj);
        Integer currentVersion = obj.getVersion();
        BankTransfer merged = bankTransferService.updateBankTransfer(obj);
        bankTransferRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BankTransfer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BankTransferIntegrationTest.testSaveBankTransfer() {
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", dod.getRandomBankTransfer());
        BankTransfer obj = dod.getNewTransientBankTransfer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BankTransfer' identifier to be null", obj.getId());
        bankTransferService.saveBankTransfer(obj);
        bankTransferRepository.flush();
        Assert.assertNotNull("Expected 'BankTransfer' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BankTransferIntegrationTest.testDeleteBankTransfer() {
        BankTransfer obj = dod.getRandomBankTransfer();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BankTransfer' failed to provide an identifier", id);
        obj = bankTransferService.findBankTransfer(id);
        bankTransferService.deleteBankTransfer(obj);
        bankTransferRepository.flush();
        Assert.assertNull("Failed to remove 'BankTransfer' with identifier '" + id + "'", bankTransferService.findBankTransfer(id));
    }
    
}
