// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import org.springframework.beans.factory.annotation.Configurable;
import orko.dev.controlgastos.model.BankAccountIntegrationTest;

privileged aspect BankAccountIntegrationTest_Roo_Configurable {
    
    declare @type: BankAccountIntegrationTest: @Configurable;
    
}
