// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.BudgetEntryDataOnDemand;
import orko.dev.controlgastos.model.BudgetEntryIntegrationTest;
import orko.dev.controlgastos.repository.BudgetEntryRepository;
import orko.dev.controlgastos.service.BudgetEntryService;

privileged aspect BudgetEntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BudgetEntryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BudgetEntryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BudgetEntryIntegrationTest: @Transactional;
    
    @Autowired
    private BudgetEntryDataOnDemand BudgetEntryIntegrationTest.dod;
    
    @Autowired
    BudgetEntryService BudgetEntryIntegrationTest.budgetEntryService;
    
    @Autowired
    BudgetEntryRepository BudgetEntryIntegrationTest.budgetEntryRepository;
    
    @Test
    public void BudgetEntryIntegrationTest.testCountAllBudgetEntrys() {
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", dod.getRandomBudgetEntry());
        long count = budgetEntryService.countAllBudgetEntrys();
        Assert.assertTrue("Counter for 'BudgetEntry' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BudgetEntryIntegrationTest.testFindBudgetEntry() {
        BudgetEntry obj = dod.getRandomBudgetEntry();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to provide an identifier", id);
        obj = budgetEntryService.findBudgetEntry(id);
        Assert.assertNotNull("Find method for 'BudgetEntry' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BudgetEntry' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BudgetEntryIntegrationTest.testFindAllBudgetEntrys() {
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", dod.getRandomBudgetEntry());
        long count = budgetEntryService.countAllBudgetEntrys();
        Assert.assertTrue("Too expensive to perform a find all test for 'BudgetEntry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BudgetEntry> result = budgetEntryService.findAllBudgetEntrys();
        Assert.assertNotNull("Find all method for 'BudgetEntry' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BudgetEntry' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BudgetEntryIntegrationTest.testFindBudgetEntryEntries() {
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", dod.getRandomBudgetEntry());
        long count = budgetEntryService.countAllBudgetEntrys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BudgetEntry> result = budgetEntryService.findBudgetEntryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BudgetEntry' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BudgetEntry' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BudgetEntryIntegrationTest.testFlush() {
        BudgetEntry obj = dod.getRandomBudgetEntry();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to provide an identifier", id);
        obj = budgetEntryService.findBudgetEntry(id);
        Assert.assertNotNull("Find method for 'BudgetEntry' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBudgetEntry(obj);
        Integer currentVersion = obj.getVersion();
        budgetEntryRepository.flush();
        Assert.assertTrue("Version for 'BudgetEntry' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BudgetEntryIntegrationTest.testUpdateBudgetEntryUpdate() {
        BudgetEntry obj = dod.getRandomBudgetEntry();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to provide an identifier", id);
        obj = budgetEntryService.findBudgetEntry(id);
        boolean modified =  dod.modifyBudgetEntry(obj);
        Integer currentVersion = obj.getVersion();
        BudgetEntry merged = budgetEntryService.updateBudgetEntry(obj);
        budgetEntryRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BudgetEntry' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BudgetEntryIntegrationTest.testSaveBudgetEntry() {
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", dod.getRandomBudgetEntry());
        BudgetEntry obj = dod.getNewTransientBudgetEntry(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BudgetEntry' identifier to be null", obj.getId());
        budgetEntryService.saveBudgetEntry(obj);
        budgetEntryRepository.flush();
        Assert.assertNotNull("Expected 'BudgetEntry' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BudgetEntryIntegrationTest.testDeleteBudgetEntry() {
        BudgetEntry obj = dod.getRandomBudgetEntry();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BudgetEntry' failed to provide an identifier", id);
        obj = budgetEntryService.findBudgetEntry(id);
        budgetEntryService.deleteBudgetEntry(obj);
        budgetEntryRepository.flush();
        Assert.assertNull("Failed to remove 'BudgetEntry' with identifier '" + id + "'", budgetEntryService.findBudgetEntry(id));
    }
    
}
