// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.EconomicFactDataOnDemand;
import orko.dev.controlgastos.model.EconomicFactIntegrationTest;
import orko.dev.controlgastos.repository.EconomicFactRepository;
import orko.dev.controlgastos.service.EconomicFactService;

privileged aspect EconomicFactIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EconomicFactIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EconomicFactIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EconomicFactIntegrationTest: @Transactional;
    
    @Autowired
    private EconomicFactDataOnDemand EconomicFactIntegrationTest.dod;
    
    @Autowired
    EconomicFactService EconomicFactIntegrationTest.economicFactService;
    
    @Autowired
    EconomicFactRepository EconomicFactIntegrationTest.economicFactRepository;
    
    @Test
    public void EconomicFactIntegrationTest.testCountAllEconomicFacts() {
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", dod.getRandomEconomicFact());
        long count = economicFactService.countAllEconomicFacts();
        Assert.assertTrue("Counter for 'EconomicFact' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EconomicFactIntegrationTest.testFindEconomicFact() {
        EconomicFact obj = dod.getRandomEconomicFact();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to provide an identifier", id);
        obj = economicFactService.findEconomicFact(id);
        Assert.assertNotNull("Find method for 'EconomicFact' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EconomicFact' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EconomicFactIntegrationTest.testFindAllEconomicFacts() {
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", dod.getRandomEconomicFact());
        long count = economicFactService.countAllEconomicFacts();
        Assert.assertTrue("Too expensive to perform a find all test for 'EconomicFact', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EconomicFact> result = economicFactService.findAllEconomicFacts();
        Assert.assertNotNull("Find all method for 'EconomicFact' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EconomicFact' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EconomicFactIntegrationTest.testFindEconomicFactEntries() {
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", dod.getRandomEconomicFact());
        long count = economicFactService.countAllEconomicFacts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EconomicFact> result = economicFactService.findEconomicFactEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EconomicFact' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EconomicFact' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EconomicFactIntegrationTest.testFlush() {
        EconomicFact obj = dod.getRandomEconomicFact();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to provide an identifier", id);
        obj = economicFactService.findEconomicFact(id);
        Assert.assertNotNull("Find method for 'EconomicFact' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEconomicFact(obj);
        Integer currentVersion = obj.getVersion();
        economicFactRepository.flush();
        Assert.assertTrue("Version for 'EconomicFact' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EconomicFactIntegrationTest.testUpdateEconomicFactUpdate() {
        EconomicFact obj = dod.getRandomEconomicFact();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to provide an identifier", id);
        obj = economicFactService.findEconomicFact(id);
        boolean modified =  dod.modifyEconomicFact(obj);
        Integer currentVersion = obj.getVersion();
        EconomicFact merged = economicFactService.updateEconomicFact(obj);
        economicFactRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EconomicFact' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EconomicFactIntegrationTest.testSaveEconomicFact() {
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", dod.getRandomEconomicFact());
        EconomicFact obj = dod.getNewTransientEconomicFact(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EconomicFact' identifier to be null", obj.getId());
        economicFactService.saveEconomicFact(obj);
        economicFactRepository.flush();
        Assert.assertNotNull("Expected 'EconomicFact' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EconomicFactIntegrationTest.testDeleteEconomicFact() {
        EconomicFact obj = dod.getRandomEconomicFact();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EconomicFact' failed to provide an identifier", id);
        obj = economicFactService.findEconomicFact(id);
        economicFactService.deleteEconomicFact(obj);
        economicFactRepository.flush();
        Assert.assertNull("Failed to remove 'EconomicFact' with identifier '" + id + "'", economicFactService.findEconomicFact(id));
    }
    
}
