// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.EntryIntegrationTest;
import orko.dev.controlgastos.repository.EntryRepository;

privileged aspect EntryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EntryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EntryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EntryIntegrationTest: @Transactional;
    
    @Autowired
    EntryRepository EntryIntegrationTest.entryRepository;
    
    @Test
    public void EntryIntegrationTest.testCountAllEntrys() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        long count = entryService.countAllEntrys();
        Assert.assertTrue("Counter for 'Entry' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EntryIntegrationTest.testFindEntry() {
        Entry obj = dod.getRandomEntry();
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide an identifier", id);
        obj = entryService.findEntry(id);
        Assert.assertNotNull("Find method for 'Entry' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Entry' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EntryIntegrationTest.testFindAllEntrys() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        long count = entryService.countAllEntrys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Entry', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Entry> result = entryService.findAllEntrys();
        Assert.assertNotNull("Find all method for 'Entry' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Entry' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EntryIntegrationTest.testFindEntryEntries() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        long count = entryService.countAllEntrys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Entry> result = entryService.findEntryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Entry' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Entry' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EntryIntegrationTest.testFlush() {
        Entry obj = dod.getRandomEntry();
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide an identifier", id);
        obj = entryService.findEntry(id);
        Assert.assertNotNull("Find method for 'Entry' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEntry(obj);
        Integer currentVersion = obj.getVersion();
        entryRepository.flush();
        Assert.assertTrue("Version for 'Entry' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EntryIntegrationTest.testUpdateEntryUpdate() {
        Entry obj = dod.getRandomEntry();
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide an identifier", id);
        obj = entryService.findEntry(id);
        boolean modified =  dod.modifyEntry(obj);
        Integer currentVersion = obj.getVersion();
        Entry merged = entryService.updateEntry(obj);
        entryRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Entry' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EntryIntegrationTest.testSaveEntry() {
        Assert.assertNotNull("Data on demand for 'Entry' failed to initialize correctly", dod.getRandomEntry());
        Entry obj = dod.getNewTransientEntry(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Entry' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Entry' identifier to be null", obj.getId());
        entryService.saveEntry(obj);
        entryRepository.flush();
        Assert.assertNotNull("Expected 'Entry' identifier to no longer be null", obj.getId());
    }
    
}
