// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;
import orko.dev.controlgastos.model.BankAccount;
import orko.dev.controlgastos.model.BankTransfer;
import orko.dev.controlgastos.model.Budget;
import orko.dev.controlgastos.model.BudgetEntry;
import orko.dev.controlgastos.model.EconomicFact;
import orko.dev.controlgastos.model.Entry;
import orko.dev.controlgastos.model.security.Authority;
import orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment;
import orko.dev.controlgastos.model.security.Principal;
import orko.dev.controlgastos.service.BankAccountService;
import orko.dev.controlgastos.service.BankTransferService;
import orko.dev.controlgastos.service.BudgetEntryService;
import orko.dev.controlgastos.service.BudgetService;
import orko.dev.controlgastos.service.EconomicFactService;
import orko.dev.controlgastos.service.EntryService;
import orko.dev.controlgastos.service.security.AuthorityPrincipalAssignmentService;
import orko.dev.controlgastos.service.security.AuthorityService;
import orko.dev.controlgastos.service.security.PrincipalService;
import orko.dev.controlgastos.web.ApplicationConversionServiceFactoryBean;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    @Autowired
    BankAccountService ApplicationConversionServiceFactoryBean.bankAccountService;
    
    @Autowired
    BankTransferService ApplicationConversionServiceFactoryBean.bankTransferService;
    
    @Autowired
    BudgetService ApplicationConversionServiceFactoryBean.budgetService;
    
    @Autowired
    BudgetEntryService ApplicationConversionServiceFactoryBean.budgetEntryService;
    
    @Autowired
    EconomicFactService ApplicationConversionServiceFactoryBean.economicFactService;
    
    @Autowired
    EntryService ApplicationConversionServiceFactoryBean.entryService;
    
    @Autowired
    AuthorityService ApplicationConversionServiceFactoryBean.authorityService;
    
    @Autowired
    AuthorityPrincipalAssignmentService ApplicationConversionServiceFactoryBean.authorityPrincipalAssignmentService;
    
    @Autowired
    PrincipalService ApplicationConversionServiceFactoryBean.principalService;
    
    public Converter<Long, BankAccount> ApplicationConversionServiceFactoryBean.getIdToBankAccountConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.BankAccount>() {
            public orko.dev.controlgastos.model.BankAccount convert(java.lang.Long id) {
                return bankAccountService.findBankAccount(id);
            }
        };
    }
    
    public Converter<String, BankAccount> ApplicationConversionServiceFactoryBean.getStringToBankAccountConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.BankAccount>() {
            public orko.dev.controlgastos.model.BankAccount convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), BankAccount.class);
            }
        };
    }
    
    public Converter<BankTransfer, String> ApplicationConversionServiceFactoryBean.getBankTransferToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<orko.dev.controlgastos.model.BankTransfer, java.lang.String>() {
            public String convert(BankTransfer bankTransfer) {
                return new StringBuilder().append(bankTransfer.getDescription()).append(' ').append(bankTransfer.getAmount()).append(' ').append(bankTransfer.getDate()).toString();
            }
        };
    }
    
    public Converter<Long, BankTransfer> ApplicationConversionServiceFactoryBean.getIdToBankTransferConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.BankTransfer>() {
            public orko.dev.controlgastos.model.BankTransfer convert(java.lang.Long id) {
                return bankTransferService.findBankTransfer(id);
            }
        };
    }
    
    public Converter<String, BankTransfer> ApplicationConversionServiceFactoryBean.getStringToBankTransferConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.BankTransfer>() {
            public orko.dev.controlgastos.model.BankTransfer convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), BankTransfer.class);
            }
        };
    }
    
    public Converter<Budget, String> ApplicationConversionServiceFactoryBean.getBudgetToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<orko.dev.controlgastos.model.Budget, java.lang.String>() {
            public String convert(Budget budget) {
                return new StringBuilder().append(budget.getDescription()).toString();
            }
        };
    }
    
    public Converter<Long, Budget> ApplicationConversionServiceFactoryBean.getIdToBudgetConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.Budget>() {
            public orko.dev.controlgastos.model.Budget convert(java.lang.Long id) {
                return budgetService.findBudget(id);
            }
        };
    }
    
    public Converter<String, Budget> ApplicationConversionServiceFactoryBean.getStringToBudgetConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.Budget>() {
            public orko.dev.controlgastos.model.Budget convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Budget.class);
            }
        };
    }
    
    public Converter<BudgetEntry, String> ApplicationConversionServiceFactoryBean.getBudgetEntryToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<orko.dev.controlgastos.model.BudgetEntry, java.lang.String>() {
            public String convert(BudgetEntry budgetEntry) {
                return new StringBuilder().append(budgetEntry.getAmount()).toString();
            }
        };
    }
    
    public Converter<Long, BudgetEntry> ApplicationConversionServiceFactoryBean.getIdToBudgetEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.BudgetEntry>() {
            public orko.dev.controlgastos.model.BudgetEntry convert(java.lang.Long id) {
                return budgetEntryService.findBudgetEntry(id);
            }
        };
    }
    
    public Converter<String, BudgetEntry> ApplicationConversionServiceFactoryBean.getStringToBudgetEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.BudgetEntry>() {
            public orko.dev.controlgastos.model.BudgetEntry convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), BudgetEntry.class);
            }
        };
    }
    
    public Converter<EconomicFact, String> ApplicationConversionServiceFactoryBean.getEconomicFactToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<orko.dev.controlgastos.model.EconomicFact, java.lang.String>() {
            public String convert(EconomicFact economicFact) {
                return new StringBuilder().append(economicFact.getDescription()).append(' ').append(economicFact.getAmount()).append(' ').append(economicFact.getDate()).toString();
            }
        };
    }
    
    public Converter<Long, EconomicFact> ApplicationConversionServiceFactoryBean.getIdToEconomicFactConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.EconomicFact>() {
            public orko.dev.controlgastos.model.EconomicFact convert(java.lang.Long id) {
                return economicFactService.findEconomicFact(id);
            }
        };
    }
    
    public Converter<String, EconomicFact> ApplicationConversionServiceFactoryBean.getStringToEconomicFactConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.EconomicFact>() {
            public orko.dev.controlgastos.model.EconomicFact convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), EconomicFact.class);
            }
        };
    }
    
    public Converter<Long, Entry> ApplicationConversionServiceFactoryBean.getIdToEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.Entry>() {
            public orko.dev.controlgastos.model.Entry convert(java.lang.Long id) {
                return entryService.findEntry(id);
            }
        };
    }
    
    public Converter<String, Entry> ApplicationConversionServiceFactoryBean.getStringToEntryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.Entry>() {
            public orko.dev.controlgastos.model.Entry convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Entry.class);
            }
        };
    }
    
    public Converter<Authority, String> ApplicationConversionServiceFactoryBean.getAuthorityToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<orko.dev.controlgastos.model.security.Authority, java.lang.String>() {
            public String convert(Authority authority) {
                return new StringBuilder().append(authority.getAuthority()).toString();
            }
        };
    }
    
    public Converter<Long, Authority> ApplicationConversionServiceFactoryBean.getIdToAuthorityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.security.Authority>() {
            public orko.dev.controlgastos.model.security.Authority convert(java.lang.Long id) {
                return authorityService.findAuthority(id);
            }
        };
    }
    
    public Converter<String, Authority> ApplicationConversionServiceFactoryBean.getStringToAuthorityConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.security.Authority>() {
            public orko.dev.controlgastos.model.security.Authority convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Authority.class);
            }
        };
    }
    
    public Converter<AuthorityPrincipalAssignment, String> ApplicationConversionServiceFactoryBean.getAuthorityPrincipalAssignmentToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment, java.lang.String>() {
            public String convert(AuthorityPrincipalAssignment authorityPrincipalAssignment) {
                return "(no displayable fields)";
            }
        };
    }
    
    public Converter<Long, AuthorityPrincipalAssignment> ApplicationConversionServiceFactoryBean.getIdToAuthorityPrincipalAssignmentConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment>() {
            public orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment convert(java.lang.Long id) {
                return authorityPrincipalAssignmentService.findAuthorityPrincipalAssignment(id);
            }
        };
    }
    
    public Converter<String, AuthorityPrincipalAssignment> ApplicationConversionServiceFactoryBean.getStringToAuthorityPrincipalAssignmentConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment>() {
            public orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), AuthorityPrincipalAssignment.class);
            }
        };
    }
    
    public Converter<Long, Principal> ApplicationConversionServiceFactoryBean.getIdToPrincipalConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, orko.dev.controlgastos.model.security.Principal>() {
            public orko.dev.controlgastos.model.security.Principal convert(java.lang.Long id) {
                return principalService.findPrincipal(id);
            }
        };
    }
    
    public Converter<String, Principal> ApplicationConversionServiceFactoryBean.getStringToPrincipalConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, orko.dev.controlgastos.model.security.Principal>() {
            public orko.dev.controlgastos.model.security.Principal convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Principal.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getBankAccountToStringConverter());
        registry.addConverter(getIdToBankAccountConverter());
        registry.addConverter(getStringToBankAccountConverter());
        registry.addConverter(getBankTransferToStringConverter());
        registry.addConverter(getIdToBankTransferConverter());
        registry.addConverter(getStringToBankTransferConverter());
        registry.addConverter(getBudgetToStringConverter());
        registry.addConverter(getIdToBudgetConverter());
        registry.addConverter(getStringToBudgetConverter());
        registry.addConverter(getBudgetEntryToStringConverter());
        registry.addConverter(getIdToBudgetEntryConverter());
        registry.addConverter(getStringToBudgetEntryConverter());
        registry.addConverter(getEconomicFactToStringConverter());
        registry.addConverter(getIdToEconomicFactConverter());
        registry.addConverter(getStringToEconomicFactConverter());
        registry.addConverter(getEntryToStringConverter());
        registry.addConverter(getIdToEntryConverter());
        registry.addConverter(getStringToEntryConverter());
        registry.addConverter(getAuthorityToStringConverter());
        registry.addConverter(getIdToAuthorityConverter());
        registry.addConverter(getStringToAuthorityConverter());
        registry.addConverter(getAuthorityPrincipalAssignmentToStringConverter());
        registry.addConverter(getIdToAuthorityPrincipalAssignmentConverter());
        registry.addConverter(getStringToAuthorityPrincipalAssignmentConverter());
        registry.addConverter(getPrincipalToStringConverter());
        registry.addConverter(getIdToPrincipalConverter());
        registry.addConverter(getStringToPrincipalConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
