// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.web;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;
import orko.dev.controlgastos.model.BankTransfer;
import orko.dev.controlgastos.service.BankAccountService;
import orko.dev.controlgastos.service.BankTransferService;
import orko.dev.controlgastos.service.security.PrincipalService;
import orko.dev.controlgastos.web.BankTransferController;

privileged aspect BankTransferController_Roo_Controller {
    
    @Autowired
    BankTransferService BankTransferController.bankTransferService;
    
    @Autowired
    BankAccountService BankTransferController.bankAccountService;
    
    @Autowired
    PrincipalService BankTransferController.principalService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String BankTransferController.create(@Valid BankTransfer bankTransfer, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, bankTransfer);
            return "banktransfers/create";
        }
        uiModel.asMap().clear();
        bankTransferService.saveBankTransfer(bankTransfer);
        return "redirect:/banktransfers/" + encodeUrlPathSegment(bankTransfer.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String BankTransferController.createForm(Model uiModel) {
        populateEditForm(uiModel, new BankTransfer());
        List<String[]> dependencies = new ArrayList<String[]>();
        if (bankAccountService.countAllBankAccounts() == 0) {
            dependencies.add(new String[] { "bankaccount", "bankaccounts" });
        }
        if (bankAccountService.countAllBankAccounts() == 0) {
            dependencies.add(new String[] { "bankaccount", "bankaccounts" });
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "banktransfers/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String BankTransferController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("banktransfer", bankTransferService.findBankTransfer(id));
        uiModel.addAttribute("itemId", id);
        return "banktransfers/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String BankTransferController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("banktransfers", bankTransferService.findBankTransferEntries(firstResult, sizeNo));
            float nrOfPages = (float) bankTransferService.countAllBankTransfers() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("banktransfers", bankTransferService.findAllBankTransfers());
        }
        addDateTimeFormatPatterns(uiModel);
        return "banktransfers/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String BankTransferController.update(@Valid BankTransfer bankTransfer, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, bankTransfer);
            return "banktransfers/update";
        }
        uiModel.asMap().clear();
        bankTransferService.updateBankTransfer(bankTransfer);
        return "redirect:/banktransfers/" + encodeUrlPathSegment(bankTransfer.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String BankTransferController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, bankTransferService.findBankTransfer(id));
        return "banktransfers/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String BankTransferController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        BankTransfer bankTransfer = bankTransferService.findBankTransfer(id);
        bankTransferService.deleteBankTransfer(bankTransfer);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/banktransfers";
    }
    
    void BankTransferController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("bankTransfer_date_date_format", DateTimeFormat.patternForStyle("S-", LocaleContextHolder.getLocale()));
    }
    
    void BankTransferController.populateEditForm(Model uiModel, BankTransfer bankTransfer) {
        uiModel.addAttribute("bankTransfer", bankTransfer);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("bankaccounts", bankAccountService.findAllBankAccounts());
        uiModel.addAttribute("principals", principalService.findAllPrincipals());
    }
    
    String BankTransferController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
