// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.web;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;
import orko.dev.controlgastos.model.Entry;
import orko.dev.controlgastos.service.EntryService;
import orko.dev.controlgastos.web.EntryController;

privileged aspect EntryController_Roo_Controller {
    
    @Autowired
    EntryService EntryController.entryService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String EntryController.create(@Valid Entry entry, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, entry);
            return "entrys/create";
        }
        uiModel.asMap().clear();
        entryService.saveEntry(entry);
        return "redirect:/entrys/" + encodeUrlPathSegment(entry.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String EntryController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("entry", entryService.findEntry(id));
        uiModel.addAttribute("itemId", id);
        return "entrys/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String EntryController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("entrys", entryService.findEntryEntries(firstResult, sizeNo));
            float nrOfPages = (float) entryService.countAllEntrys() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("entrys", entryService.findAllEntrys());
        }
        return "entrys/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String EntryController.update(@Valid Entry entry, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, entry);
            return "entrys/update";
        }
        uiModel.asMap().clear();
        entryService.updateEntry(entry);
        return "redirect:/entrys/" + encodeUrlPathSegment(entry.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String EntryController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, entryService.findEntry(id));
        return "entrys/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String EntryController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Entry entry = entryService.findEntry(id);
        entryService.deleteEntry(entry);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/entrys";
    }
    
    String EntryController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
