// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.BankAccount;
import orko.dev.controlgastos.repository.BankAccountRepository;
import orko.dev.controlgastos.service.BankAccountServiceImpl;

privileged aspect BankAccountServiceImpl_Roo_Service {
    
    declare @type: BankAccountServiceImpl: @Service;
    
    declare @type: BankAccountServiceImpl: @Transactional;
    
    @Autowired
    BankAccountRepository BankAccountServiceImpl.bankAccountRepository;
    
    public void BankAccountServiceImpl.deleteBankAccount(BankAccount bankAccount) {
        bankAccountRepository.delete(bankAccount);
    }
    
    public BankAccount BankAccountServiceImpl.findBankAccount(Long id) {
        return bankAccountRepository.findOne(id);
    }
    
}
