// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.BankTransfer;
import orko.dev.controlgastos.service.BankTransferServiceImpl;

privileged aspect BankTransferServiceImpl_Roo_Service {
    
    declare @type: BankTransferServiceImpl: @Service;
    
    declare @type: BankTransferServiceImpl: @Transactional;
    
    public void BankTransferServiceImpl.deleteBankTransfer(BankTransfer bankTransfer) {
        bankTransferRepository.delete(bankTransfer);
    }
    
    public BankTransfer BankTransferServiceImpl.findBankTransfer(Long id) {
        return bankTransferRepository.findOne(id);
    }
    
}
