// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import java.util.List;
import orko.dev.controlgastos.model.BankTransfer;
import orko.dev.controlgastos.service.BankTransferService;

privileged aspect BankTransferService_Roo_Service {
    
    public abstract long BankTransferService.countAllBankTransfers();    
    public abstract void BankTransferService.deleteBankTransfer(BankTransfer bankTransfer);    
    public abstract BankTransfer BankTransferService.findBankTransfer(Long id);    
    public abstract List<BankTransfer> BankTransferService.findAllBankTransfers();    
    public abstract List<BankTransfer> BankTransferService.findBankTransferEntries(int firstResult, int maxResults);    
    public abstract void BankTransferService.saveBankTransfer(BankTransfer bankTransfer);    
    public abstract BankTransfer BankTransferService.updateBankTransfer(BankTransfer bankTransfer);    
}
