// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.Budget;
import orko.dev.controlgastos.repository.BudgetRepository;
import orko.dev.controlgastos.service.BudgetServiceImpl;

privileged aspect BudgetServiceImpl_Roo_Service {
    
    declare @type: BudgetServiceImpl: @Service;
    
    declare @type: BudgetServiceImpl: @Transactional;
    
    @Autowired
    BudgetRepository BudgetServiceImpl.budgetRepository;
    
    public void BudgetServiceImpl.deleteBudget(Budget budget) {
        budgetRepository.delete(budget);
    }
    
    public Budget BudgetServiceImpl.findBudget(Long id) {
        return budgetRepository.findOne(id);
    }
    
}
