// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import java.util.List;
import orko.dev.controlgastos.model.BudgetEntry;
import orko.dev.controlgastos.service.BudgetEntryService;

privileged aspect BudgetEntryService_Roo_Service {
    
    public abstract long BudgetEntryService.countAllBudgetEntrys();    
    public abstract void BudgetEntryService.deleteBudgetEntry(BudgetEntry budgetEntry);    
    public abstract BudgetEntry BudgetEntryService.findBudgetEntry(Long id);    
    public abstract List<BudgetEntry> BudgetEntryService.findAllBudgetEntrys();    
    public abstract List<BudgetEntry> BudgetEntryService.findBudgetEntryEntries(int firstResult, int maxResults);    
    public abstract void BudgetEntryService.saveBudgetEntry(BudgetEntry budgetEntry);    
    public abstract BudgetEntry BudgetEntryService.updateBudgetEntry(BudgetEntry budgetEntry);    
}
