// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.BudgetEntry;
import orko.dev.controlgastos.repository.BudgetEntryRepository;
import orko.dev.controlgastos.service.BudgetEntryServiceImpl;

privileged aspect BudgetEntryServiceImpl_Roo_Service {
    
    declare @type: BudgetEntryServiceImpl: @Service;
    
    declare @type: BudgetEntryServiceImpl: @Transactional;
    
    @Autowired
    BudgetEntryRepository BudgetEntryServiceImpl.budgetEntryRepository;
    
    public void BudgetEntryServiceImpl.deleteBudgetEntry(BudgetEntry budgetEntry) {
        budgetEntryRepository.delete(budgetEntry);
    }
    
    public BudgetEntry BudgetEntryServiceImpl.findBudgetEntry(Long id) {
        return budgetEntryRepository.findOne(id);
    }
    
}
