// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.EconomicFact;
import orko.dev.controlgastos.repository.EconomicFactRepository;
import orko.dev.controlgastos.service.EconomicFactServiceImpl;

privileged aspect EconomicFactServiceImpl_Roo_Service {
    
    declare @type: EconomicFactServiceImpl: @Service;
    
    declare @type: EconomicFactServiceImpl: @Transactional;
    
    @Autowired
    EconomicFactRepository EconomicFactServiceImpl.economicFactRepository;
    
    public void EconomicFactServiceImpl.deleteEconomicFact(EconomicFact economicFact) {
        economicFactRepository.delete(economicFact);
    }
    
    public EconomicFact EconomicFactServiceImpl.findEconomicFact(Long id) {
        return economicFactRepository.findOne(id);
    }
    
}
