// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.Entry;
import orko.dev.controlgastos.repository.EntryRepository;
import orko.dev.controlgastos.service.EntryServiceImpl;

privileged aspect EntryServiceImpl_Roo_Service {
    
    declare @type: EntryServiceImpl: @Service;
    
    declare @type: EntryServiceImpl: @Transactional;
    
    @Autowired
    EntryRepository EntryServiceImpl.entryRepository;
    
    public void EntryServiceImpl.deleteEntry(Entry entry) {
        entryRepository.delete(entry);
    }
    
    public Entry EntryServiceImpl.findEntry(Long id) {
        return entryRepository.findOne(id);
    }
    
}
