// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service;

import java.util.List;
import orko.dev.controlgastos.model.Entry;
import orko.dev.controlgastos.service.EntryService;

privileged aspect EntryService_Roo_Service {
    
    public abstract long EntryService.countAllEntrys();    
    public abstract void EntryService.deleteEntry(Entry entry);    
    public abstract Entry EntryService.findEntry(Long id);    
    public abstract List<Entry> EntryService.findAllEntrys();    
    public abstract List<Entry> EntryService.findEntryEntries(int firstResult, int maxResults);    
    public abstract void EntryService.saveEntry(Entry entry);    
    public abstract Entry EntryService.updateEntry(Entry entry);    
}
