// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import orko.dev.controlgastos.model.BankTransfer;
import orko.dev.controlgastos.repository.BankTransferRepository;

privileged aspect BankTransferRepository_Roo_Jpa_Repository {
    
    declare parents: BankTransferRepository extends JpaRepository<BankTransfer, Long>;
    
    declare parents: BankTransferRepository extends JpaSpecificationExecutor<BankTransfer>;
    
    declare @type: BankTransferRepository: @Repository;
    
}
