// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import orko.dev.controlgastos.model.BudgetEntry;
import orko.dev.controlgastos.repository.BudgetEntryRepository;

privileged aspect BudgetEntryRepository_Roo_Jpa_Repository {
    
    declare parents: BudgetEntryRepository extends JpaRepository<BudgetEntry, Long>;
    
    declare parents: BudgetEntryRepository extends JpaSpecificationExecutor<BudgetEntry>;
    
    declare @type: BudgetEntryRepository: @Repository;
    
}
