// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.web.security;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;
import orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment;
import orko.dev.controlgastos.service.security.AuthorityPrincipalAssignmentService;
import orko.dev.controlgastos.service.security.AuthorityService;
import orko.dev.controlgastos.service.security.PrincipalService;
import orko.dev.controlgastos.web.security.RoleMappingContoller;

privileged aspect RoleMappingContoller_Roo_Controller {
    
    @Autowired
    AuthorityPrincipalAssignmentService RoleMappingContoller.authorityPrincipalAssignmentService;
    
    @Autowired
    AuthorityService RoleMappingContoller.authorityService;
    
    @Autowired
    PrincipalService RoleMappingContoller.principalService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String RoleMappingContoller.create(@Valid AuthorityPrincipalAssignment authorityPrincipalAssignment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, authorityPrincipalAssignment);
            return "security/assignments/create";
        }
        uiModel.asMap().clear();
        authorityPrincipalAssignmentService.saveAuthorityPrincipalAssignment(authorityPrincipalAssignment);
        return "redirect:/security/assignments/" + encodeUrlPathSegment(authorityPrincipalAssignment.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String RoleMappingContoller.createForm(Model uiModel) {
        populateEditForm(uiModel, new AuthorityPrincipalAssignment());
        return "security/assignments/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String RoleMappingContoller.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("authorityprincipalassignment", authorityPrincipalAssignmentService.findAuthorityPrincipalAssignment(id));
        uiModel.addAttribute("itemId", id);
        return "security/assignments/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String RoleMappingContoller.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("authorityprincipalassignments", authorityPrincipalAssignmentService.findAuthorityPrincipalAssignmentEntries(firstResult, sizeNo));
            float nrOfPages = (float) authorityPrincipalAssignmentService.countAllAuthorityPrincipalAssignments() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("authorityprincipalassignments", authorityPrincipalAssignmentService.findAllAuthorityPrincipalAssignments());
        }
        return "security/assignments/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String RoleMappingContoller.update(@Valid AuthorityPrincipalAssignment authorityPrincipalAssignment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, authorityPrincipalAssignment);
            return "security/assignments/update";
        }
        uiModel.asMap().clear();
        authorityPrincipalAssignmentService.updateAuthorityPrincipalAssignment(authorityPrincipalAssignment);
        return "redirect:/security/assignments/" + encodeUrlPathSegment(authorityPrincipalAssignment.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String RoleMappingContoller.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, authorityPrincipalAssignmentService.findAuthorityPrincipalAssignment(id));
        return "security/assignments/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String RoleMappingContoller.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        AuthorityPrincipalAssignment authorityPrincipalAssignment = authorityPrincipalAssignmentService.findAuthorityPrincipalAssignment(id);
        authorityPrincipalAssignmentService.deleteAuthorityPrincipalAssignment(authorityPrincipalAssignment);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/security/assignments";
    }
    
    void RoleMappingContoller.populateEditForm(Model uiModel, AuthorityPrincipalAssignment authorityPrincipalAssignment) {
        uiModel.addAttribute("authorityPrincipalAssignment", authorityPrincipalAssignment);
        uiModel.addAttribute("authoritys", authorityService.findAllAuthoritys());
        uiModel.addAttribute("principals", principalService.findAllPrincipals());
    }
    
    String RoleMappingContoller.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
