// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.web.security;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;
import orko.dev.controlgastos.model.security.Authority;
import orko.dev.controlgastos.service.security.AuthorityService;
import orko.dev.controlgastos.web.security.RoleContoller;

privileged aspect RoleContoller_Roo_Controller {
    
    @Autowired
    AuthorityService RoleContoller.authorityService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String RoleContoller.create(@Valid Authority authority, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, authority);
            return "security/roles/create";
        }
        uiModel.asMap().clear();
        authorityService.saveAuthority(authority);
        return "redirect:/security/roles/" + encodeUrlPathSegment(authority.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String RoleContoller.createForm(Model uiModel) {
        populateEditForm(uiModel, new Authority());
        return "security/roles/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String RoleContoller.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("authority", authorityService.findAuthority(id));
        uiModel.addAttribute("itemId", id);
        return "security/roles/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String RoleContoller.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("authoritys", authorityService.findAuthorityEntries(firstResult, sizeNo));
            float nrOfPages = (float) authorityService.countAllAuthoritys() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("authoritys", authorityService.findAllAuthoritys());
        }
        return "security/roles/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String RoleContoller.update(@Valid Authority authority, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, authority);
            return "security/roles/update";
        }
        uiModel.asMap().clear();
        authorityService.updateAuthority(authority);
        return "redirect:/security/roles/" + encodeUrlPathSegment(authority.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String RoleContoller.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, authorityService.findAuthority(id));
        return "security/roles/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String RoleContoller.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Authority authority = authorityService.findAuthority(id);
        authorityService.deleteAuthority(authority);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/security/roles";
    }
    
    void RoleContoller.populateEditForm(Model uiModel, Authority authority) {
        uiModel.addAttribute("authority", authority);
    }
    
    String RoleContoller.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
