// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.math.BigDecimal;
import java.util.Date;
import orko.dev.controlgastos.model.BankAccount;
import orko.dev.controlgastos.model.BankTransfer;
import orko.dev.controlgastos.model.security.Principal;

privileged aspect BankTransfer_Roo_JavaBean {
    
    public String BankTransfer.getDescription() {
        return this.description;
    }
    
    public void BankTransfer.setDescription(String description) {
        this.description = description;
    }
    
    public BigDecimal BankTransfer.getAmount() {
        return this.amount;
    }
    
    public void BankTransfer.setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    public Date BankTransfer.getDate() {
        return this.date;
    }
    
    public void BankTransfer.setDate(Date date) {
        this.date = date;
    }
    
    public BankAccount BankTransfer.getBankAccountDest() {
        return this.bankAccountDest;
    }
    
    public void BankTransfer.setBankAccountDest(BankAccount bankAccountDest) {
        this.bankAccountDest = bankAccountDest;
    }
    
    public BankAccount BankTransfer.getBankAccountSrc() {
        return this.bankAccountSrc;
    }
    
    public void BankTransfer.setBankAccountSrc(BankAccount bankAccountSrc) {
        this.bankAccountSrc = bankAccountSrc;
    }
    
    public Principal BankTransfer.getUser() {
        return this.user;
    }
    
    public void BankTransfer.setUser(Principal user) {
        this.user = user;
    }
    
}
