// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import orko.dev.controlgastos.model.BankAccount;
import orko.dev.controlgastos.model.BankAccountType;
import orko.dev.controlgastos.model.security.Principal;

privileged aspect BankAccount_Roo_JavaBean {
    
    public String BankAccount.getDescription() {
        return this.description;
    }
    
    public void BankAccount.setDescription(String description) {
        this.description = description;
    }
    
    public String BankAccount.getBank() {
        return this.bank;
    }
    
    public void BankAccount.setBank(String bank) {
        this.bank = bank;
    }
    
    public BankAccountType BankAccount.getBankAccountType() {
        return this.bankAccountType;
    }
    
    public void BankAccount.setBankAccountType(BankAccountType bankAccountType) {
        this.bankAccountType = bankAccountType;
    }
    
    public Principal BankAccount.getUser() {
        return this.user;
    }
    
    public void BankAccount.setUser(Principal user) {
        this.user = user;
    }
    
}
