// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import orko.dev.controlgastos.model.BankTransfer;

privileged aspect BankTransfer_Roo_Jpa_Entity {
    
    declare @type: BankTransfer: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long BankTransfer.id;
    
    @Version
    @Column(name = "version")
    private Integer BankTransfer.version;
    
    public Long BankTransfer.getId() {
        return this.id;
    }
    
    public void BankTransfer.setId(Long id) {
        this.id = id;
    }
    
    public Integer BankTransfer.getVersion() {
        return this.version;
    }
    
    public void BankTransfer.setVersion(Integer version) {
        this.version = version;
    }
    
}
