// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.util.Set;
import orko.dev.controlgastos.model.Budget;
import orko.dev.controlgastos.model.BudgetEntry;
import orko.dev.controlgastos.model.security.Principal;

privileged aspect Budget_Roo_JavaBean {
    
    public String Budget.getDescription() {
        return this.description;
    }
    
    public void Budget.setDescription(String description) {
        this.description = description;
    }
    
    public Set<BudgetEntry> Budget.getBudgetEntries() {
        return this.budgetEntries;
    }
    
    public void Budget.setBudgetEntries(Set<BudgetEntry> budgetEntries) {
        this.budgetEntries = budgetEntries;
    }
    
    public Principal Budget.getUser() {
        return this.user;
    }
    
    public void Budget.setUser(Principal user) {
        this.user = user;
    }
    
}
