// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.math.BigDecimal;
import orko.dev.controlgastos.model.Budget;
import orko.dev.controlgastos.model.BudgetEntry;
import orko.dev.controlgastos.model.Entry;
import orko.dev.controlgastos.model.security.Principal;

privileged aspect BudgetEntry_Roo_JavaBean {
    
    public BigDecimal BudgetEntry.getAmount() {
        return this.amount;
    }
    
    public void BudgetEntry.setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    public Entry BudgetEntry.getEntry() {
        return this.entry;
    }
    
    public void BudgetEntry.setEntry(Entry entry) {
        this.entry = entry;
    }
    
    public Budget BudgetEntry.getBudget() {
        return this.budget;
    }
    
    public void BudgetEntry.setBudget(Budget budget) {
        this.budget = budget;
    }
    
    public Principal BudgetEntry.getUser() {
        return this.user;
    }
    
    public void BudgetEntry.setUser(Principal user) {
        this.user = user;
    }
    
}
