// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import orko.dev.controlgastos.model.Budget;

privileged aspect Budget_Roo_Jpa_Entity {
    
    declare @type: Budget: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Budget.id;
    
    @Version
    @Column(name = "version")
    private Integer Budget.version;
    
    public Long Budget.getId() {
        return this.id;
    }
    
    public void Budget.setId(Long id) {
        this.id = id;
    }
    
    public Integer Budget.getVersion() {
        return this.version;
    }
    
    public void Budget.setVersion(Integer version) {
        this.version = version;
    }
    
}
