// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import java.math.BigDecimal;
import java.util.Date;
import orko.dev.controlgastos.model.BankAccount;
import orko.dev.controlgastos.model.Budget;
import orko.dev.controlgastos.model.EconomicFact;
import orko.dev.controlgastos.model.Entry;
import orko.dev.controlgastos.model.security.Principal;

privileged aspect EconomicFact_Roo_JavaBean {
    
    public Entry EconomicFact.getEntry() {
        return this.entry;
    }
    
    public void EconomicFact.setEntry(Entry entry) {
        this.entry = entry;
    }
    
    public String EconomicFact.getDescription() {
        return this.description;
    }
    
    public void EconomicFact.setDescription(String description) {
        this.description = description;
    }
    
    public Budget EconomicFact.getBudget() {
        return this.budget;
    }
    
    public void EconomicFact.setBudget(Budget budget) {
        this.budget = budget;
    }
    
    public BigDecimal EconomicFact.getAmount() {
        return this.amount;
    }
    
    public void EconomicFact.setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    
    public Date EconomicFact.getDate() {
        return this.date;
    }
    
    public void EconomicFact.setDate(Date date) {
        this.date = date;
    }
    
    public BankAccount EconomicFact.getBankAccount() {
        return this.bankAccount;
    }
    
    public void EconomicFact.setBankAccount(BankAccount bankAccount) {
        this.bankAccount = bankAccount;
    }
    
    public Principal EconomicFact.getUser() {
        return this.user;
    }
    
    public void EconomicFact.setUser(Principal user) {
        this.user = user;
    }
    
}
