// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import orko.dev.controlgastos.model.Entry;

privileged aspect Entry_Roo_Jpa_Entity {
    
    declare @type: Entry: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Entry.id;
    
    @Version
    @Column(name = "version")
    private Integer Entry.version;
    
    public Long Entry.getId() {
        return this.id;
    }
    
    public void Entry.setId(Long id) {
        this.id = id;
    }
    
    public Integer Entry.getVersion() {
        return this.version;
    }
    
    public void Entry.setVersion(Integer version) {
        this.version = version;
    }
    
}
