// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model.security;

import orko.dev.controlgastos.model.security.Authority;

privileged aspect Authority_Roo_JavaBean {
    
    public String Authority.getAuthority() {
        return this.authority;
    }
    
    public void Authority.setAuthority(String authority) {
        this.authority = authority;
    }
    
}
