// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.model.security;

import orko.dev.controlgastos.model.security.Principal;

privileged aspect Principal_Roo_JavaBean {
    
    public String Principal.getUsername() {
        return this.username;
    }
    
    public void Principal.setUsername(String username) {
        this.username = username;
    }
    
    public String Principal.getPassword() {
        return this.password;
    }
    
    public void Principal.setPassword(String password) {
        this.password = password;
    }
    
    public Boolean Principal.getEnabled() {
        return this.enabled;
    }
    
    public void Principal.setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    
    public String Principal.getName() {
        return this.name;
    }
    
    public void Principal.setName(String name) {
        this.name = name;
    }
    
    public String Principal.getLastName() {
        return this.lastName;
    }
    
    public void Principal.setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public String Principal.getEmail() {
        return this.email;
    }
    
    public void Principal.setEmail(String email) {
        this.email = email;
    }
    
}
