// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orko.dev.controlgastos.service.security;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import orko.dev.controlgastos.model.security.AuthorityPrincipalAssignment;
import orko.dev.controlgastos.repository.security.AuthorityPrincipalAssignmentRepository;
import orko.dev.controlgastos.service.security.AuthorityPrincipalAssignmentServiceImpl;

privileged aspect AuthorityPrincipalAssignmentServiceImpl_Roo_Service {
    
    declare @type: AuthorityPrincipalAssignmentServiceImpl: @Service;
    
    declare @type: AuthorityPrincipalAssignmentServiceImpl: @Transactional;
    
    @Autowired
    AuthorityPrincipalAssignmentRepository AuthorityPrincipalAssignmentServiceImpl.authorityPrincipalAssignmentRepository;
    
    public long AuthorityPrincipalAssignmentServiceImpl.countAllAuthorityPrincipalAssignments() {
        return authorityPrincipalAssignmentRepository.count();
    }
    
    public void AuthorityPrincipalAssignmentServiceImpl.deleteAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment) {
        authorityPrincipalAssignmentRepository.delete(authorityPrincipalAssignment);
    }
    
    public AuthorityPrincipalAssignment AuthorityPrincipalAssignmentServiceImpl.findAuthorityPrincipalAssignment(Long id) {
        return authorityPrincipalAssignmentRepository.findOne(id);
    }
    
    public List<AuthorityPrincipalAssignment> AuthorityPrincipalAssignmentServiceImpl.findAllAuthorityPrincipalAssignments() {
        return authorityPrincipalAssignmentRepository.findAll();
    }
    
    public List<AuthorityPrincipalAssignment> AuthorityPrincipalAssignmentServiceImpl.findAuthorityPrincipalAssignmentEntries(int firstResult, int maxResults) {
        return authorityPrincipalAssignmentRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void AuthorityPrincipalAssignmentServiceImpl.saveAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment) {
        authorityPrincipalAssignmentRepository.save(authorityPrincipalAssignment);
    }
    
    public AuthorityPrincipalAssignment AuthorityPrincipalAssignmentServiceImpl.updateAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment) {
        return authorityPrincipalAssignmentRepository.save(authorityPrincipalAssignment);
    }
    
}
